version: '3.8'

services:
  cryptbot:
    container_name: cryptbot
    image: sacwoo/cryptbot:latest  # Pull the latest image from Docker Hub
    restart: unless-stopped
    network_mode: bridge
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - /mnt/user/appdata/cryptbot:/app  # Ensure this directory exists
    ports:
      - "8080:80"
